executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} && sbatch --nodes=1 --ntasks=1
  --cpus-per-task={resources.threads} --mem={resources.mem_mb}
  --job-name=smk-{rule}-{wildcards}
  --output=logs/{rule}/{rule}-{wildcards}-%j.out --parsable
default-resources:
  - mem_mb=1000
  - threads=8
restart-times: 0
max-jobs-per-second: 45
max-status-checks-per-second: 2
local-cores: 1
latency-wait: 30
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-generic-cancel-cmd: scancel
